// <auto-generated />
using System;
using EShoppingZone.Orders.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EShoppingZone.Orders.API.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20260424095134_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("EShoppingZone.Orders.API.Domain.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModeOfPayment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EShoppingZone.Orders.API.Domain.Order", b =>
                {
                    b.OwnsOne("EShoppingZone.Orders.API.Domain.OrderAddress", "Address", b1 =>
                        {
                            b1.Property<int>("OrderId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_City");

                            b1.Property<int>("CustomerId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Address_CustomerId");

                            b1.Property<string>("FlatNumber")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_FlatNumber");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_FullName");

                            b1.Property<long>("MobileNumber")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Address_MobileNumber");

                            b1.Property<int>("Pincode")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Address_Pincode");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_State");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
